package net.minecraft.client.util;

import android.bluetooth.BluetoothServerSocket;
import android.content.PeriodicSync;
import android.graphics.BitmapRegionDecoder;
import android.graphics.ComposePathEffect;
import android.os.StatFs;
import android.text.style.ScaleXSpan;
import android.view.inputmethod.InputConnectionWrapper;
import breeze.linalg.Axis;
import breeze.linalg.convert;
import breeze.optimize.NaNHistory;
import breeze.optimize.proximal.ProjectEquality;
import breeze.optimize.proximal.ProximalHuber;
import breeze.stats.distributions.Multinomial;
import breeze.util.PairIndex;
import com.alibaba.druid.pool.DataSourceClosedException;
import com.alibaba.druid.pool.DruidDataSourceStatLoggerAdapter;
import com.alibaba.druid.pool.vendor.MSSQLValidConnectionChecker;
import com.alibaba.druid.sql.ast.expr.SQLTinyIntExpr;
import com.alibaba.druid.sql.ast.statement.SQLAlterIndexStatement;
import com.alibaba.druid.sql.ast.statement.SQLAlterTableItem;
import com.alibaba.druid.sql.ast.statement.SQLAlterTableSetFileFormat;
import com.alibaba.druid.sql.dialect.hive.visitor.HiveASTVisitorAdapter;
import com.alibaba.druid.sql.dialect.mysql.ast.statement.MysqlCreateFullTextCharFilterStatement;
import com.alibaba.druid.sql.dialect.odps.parser.OdpsLexer;
import com.alibaba.druid.sql.dialect.oracle.ast.OracleDataTypeIntervalDay;
import com.alibaba.druid.sql.dialect.redshift.parser.RedshiftExprParser;
import com.alibaba.druid.sql.dialect.snowflake.SnowflakeStatementParser;
import com.alibaba.druid.sql.dialect.starrocks.ast.statement.StarRocksCreateResourceStatement;
import com.alibaba.druid.support.opds.udf.SqlPatternHash;
import com.alibaba.druid.support.profile.ProfileEntryStatValue;
import com.sk89q.jchronic.repeaters.RepeaterWeekend;
import com.sk89q.jchronic.utils.Tick;
import com.sk89q.minecraft.util.commands.CommandUsageException;
import com.sk89q.worldedit.antlr4.runtime.atn.LexerModeAction;
import com.sk89q.worldedit.antlr4.runtime.atn.LexerMoreAction;
import com.sk89q.worldedit.extension.input.InputParseException;
import com.sk89q.worldedit.forge.ForgeBiomeRegistry;
import com.sk89q.worldedit.function.mask.BlockMask;
import com.sk89q.worldedit.function.operation.Operations;
import com.sk89q.worldedit.regions.Regions;
import com.sk89q.worldedit.regions.iterator.RegionIterator;
import com.sk89q.worldedit.regions.shape.WorldEditExpressionEnvironment;
import com.sk89q.worldedit.util.eventbus.EventBus;
import com.sk89q.worldedit.util.gson.VectorAdapter;
import net.daporkchop.fp2.client.gui.access.ReflectiveGuiObjectAccess;
import net.daporkchop.fp2.compat.vanilla.biome.layer.ITranslationLayer;
import net.daporkchop.fp2.compat.vanilla.biome.layer.c.NativeFastLayerIsland;
import net.daporkchop.fp2.util.threading.ThreadingHelper;
import net.daporkchop.lib.common.ref.JavaLateThreadRef;
import net.daporkchop.lib.common.util.exception.ReadOnlyException;
import net.daporkchop.lib.compression.zstd.ZstdProvider;
import net.daporkchop.lib.math.interpolation.CubicInterpolation;
import net.daporkchop.lib.math.vector.l.Vec2lM;
import net.daporkchop.lib.primitive.lambda.CharObjDoubleFunction;
import net.daporkchop.lib.primitive.lambda.CharShortFunction;
import net.daporkchop.lib.primitive.lambda.DoubleShortFunction;
import net.daporkchop.lib.primitive.lambda.FloatDoubleFunction;
import net.daporkchop.lib.primitive.lambda.FloatIntBoolConsumer;
import net.daporkchop.lib.primitive.lambda.FloatLongLongConsumer;
import net.daporkchop.lib.primitive.lambda.IntBoolByteFunction;
import net.daporkchop.lib.primitive.lambda.IntShortLongConsumer;
import net.daporkchop.lib.primitive.lambda.LongFloatObjFunction;
import net.daporkchop.lib.primitive.lambda.LongLongBoolConsumer;
import net.daporkchop.lib.primitive.lambda.ObjDoubleCharConsumer;
import net.daporkchop.lib.primitive.lambda.ObjObjCharFunction;
import net.daporkchop.lib.primitive.lambda.ShortCharByteFunction;
import net.daporkchop.lib.primitive.lambda.ShortLongByteConsumer;
import net.daporkchop.lib.primitive.list.ShortList;
import net.daporkchop.lib.primitive.map.CharObjMap;
import net.daporkchop.lib.primitive.map.FloatLongMap;
import net.daporkchop.lib.primitive.map.LongLongMap;
import net.daporkchop.lib.primitive.map.open.ByteDoubleOpenHashMap;
import net.minecraft.block.BlockCake;
import net.minecraft.block.BlockMycelium;
import net.minecraft.block.BlockRedstoneRepeater;
import net.minecraft.client.gui.chat.NormalChatListener;
import net.minecraft.client.gui.inventory.GuiEditSign;
import net.minecraft.client.gui.recipebook.GuiButtonRecipe;
import net.minecraft.client.model.ModelArmorStand;
import net.minecraft.client.resources.IResourceManagerReloadListener;
import net.minecraft.command.CommandReload;
import net.minecraft.command.ICommand;
import net.minecraft.entity.ai.EntityAICreeperSwell;
import net.minecraft.entity.ai.EntityAILookIdle;
import net.minecraft.entity.ai.attributes.ModifiableAttributeInstance;
import net.minecraft.entity.item.EntityArmorStand;
import net.minecraft.entity.item.EntityEnderCrystal;
import net.minecraft.entity.monster.EntityEndermite;
import net.minecraft.entity.monster.EntitySilverfish;
import net.minecraft.inventory.SlotCrafting;
import net.minecraft.item.ItemFishFood;
import net.minecraft.item.ItemSaddle;
import net.minecraft.nbt.NBTTagDouble;
import net.minecraft.pathfinding.PathNavigateClimber;
import net.minecraft.tileentity.TileEntityFurnace;
import net.minecraft.tileentity.TileEntityShulkerBox;
import net.minecraft.tileentity.TileEntityStructure;
import net.minecraft.util.datafix.fixes.RidingToPassengers;
import net.minecraft.world.EnumDifficulty;
import net.minecraft.world.border.WorldBorder;
import net.minecraft.world.gen.ChunkGeneratorOverworld;
import net.minecraft.world.gen.feature.WorldGenLiquids;
import net.minecraft.world.gen.layer.IntCache;
import net.minecraft.world.storage.loot.ILootContainer;
import net.minecraftforge.client.event.GuiOpenEvent;
import net.minecraftforge.client.model.animation.ModelBlockAnimation;
import net.minecraftforge.client.model.pipeline.TRSRTransformer;
import net.minecraftforge.client.model.pipeline.TransformerConsumer;
import net.minecraftforge.common.EnumPlantType;
import net.minecraftforge.common.model.animation.IAnimationStateMachine;
import net.minecraftforge.event.entity.player.PlayerDropsEvent;
import net.minecraftforge.fluids.capability.CapabilityFluidHandler;
import net.minecraftforge.fml.client.GuiModsMissing;
import net.minecraftforge.fml.client.config.GuiSelectString;
import net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper;
import net.optifine.BlockDir;
import net.optifine.IRandomEntity;
import net.optifine.reflect.FieldLocatorFixed;
import net.optifine.reflect.ReflectorFields;
import org.postgresql.core.CommandCompleteParser;
import org.postgresql.gss.GSSInputStream;
import org.postgresql.jdbc.AutoSave;
import org.postgresql.shaded.com.ongres.scram.common.ServerFinalMessage;
import org.postgresql.shaded.com.ongres.scram.common.exception.ScramInvalidServerSignatureException;
import org.postgresql.translation.messages_de;
import org.postgresql.util.PGJDBCMain;
import org.postgresql.util.URLCoder;
import org.rocksdb.Filter;
import org.rocksdb.RocksMutableObject;

public class JsonException {
   private static void null(ModifiableAttributeInstance arg0) {
      arg0.null((InputParseException)EnumDifficulty.false, (SQLAlterTableItem)(new SQLTinyIntExpr()));
      arg0.null((InputParseException)EnumDifficulty.const, (SQLAlterTableItem)(new TRSRTransformer()));
      arg0.null((InputParseException)EnumDifficulty.null, (SQLAlterTableItem)(new RidingToPassengers()));
      arg0.null((InputParseException)EnumDifficulty.null, (SQLAlterTableItem)(new WorldEditExpressionEnvironment()));
      arg0.null((InputParseException)EnumDifficulty.null, (SQLAlterTableItem)(new convert()));
      arg0.null((InputParseException)EnumDifficulty.false, (SQLAlterTableItem)(new CharObjDoubleFunction()));
      arg0.null((InputParseException)EnumDifficulty.const, (SQLAlterTableItem)(new InputConnectionWrapper()));
      arg0.null((InputParseException)EnumDifficulty.false, (SQLAlterTableItem)(new SQLAlterIndexStatement()));
      arg0.null((InputParseException)EnumDifficulty.false, (SQLAlterTableItem)(new ZstdProvider()));
      arg0.null((InputParseException)EnumDifficulty.false, (SQLAlterTableItem)(new ShortList()));
      arg0.null((InputParseException)EnumDifficulty.false, (SQLAlterTableItem)(new LongLongMap()));
      arg0.null((InputParseException)EnumDifficulty.false, (SQLAlterTableItem)(new EntityAICreeperSwell()));
      arg0.null((InputParseException)EnumDifficulty.false, (SQLAlterTableItem)(new ProjectEquality()));
      arg0.null((InputParseException)EnumDifficulty.false, (SQLAlterTableItem)(new ITranslationLayer()));
      arg0.null((InputParseException)EnumDifficulty.null, (SQLAlterTableItem)(new GuiOpenEvent()));
      arg0.null((InputParseException)EnumDifficulty.null, (SQLAlterTableItem)(new EntityEndermite()));
      arg0.null((InputParseException)EnumDifficulty.false, (SQLAlterTableItem)(new DruidDataSourceStatLoggerAdapter()));
      arg0.null((InputParseException)EnumDifficulty.int, (SQLAlterTableItem)(new LexerModeAction()));
      arg0.null((InputParseException)EnumDifficulty.false, (SQLAlterTableItem)(new MSSQLValidConnectionChecker()));
      arg0.null((InputParseException)EnumDifficulty.false, (SQLAlterTableItem)(new OracleDataTypeIntervalDay()));
      arg0.null((InputParseException)EnumDifficulty.false, (SQLAlterTableItem)(new ReflectorFields()));
      arg0.null((InputParseException)EnumDifficulty.false, (SQLAlterTableItem)(new SnowflakeStatementParser()));
      arg0.null((InputParseException)EnumDifficulty.const, (SQLAlterTableItem)(new DataSourceClosedException()));
      arg0.null((InputParseException)EnumDifficulty.false, (SQLAlterTableItem)(new PeriodicSync()));
      arg0.null((InputParseException)EnumDifficulty.null, (SQLAlterTableItem)(new HiveASTVisitorAdapter()));
      arg0.null((InputParseException)EnumDifficulty.null, (SQLAlterTableItem)(new IntBoolByteFunction()));
      arg0.null((InputParseException)EnumDifficulty.false, (SQLAlterTableItem)(new ShortLongByteConsumer()));
      arg0.null((InputParseException)EnumDifficulty.null, (SQLAlterTableItem)(new NormalChatListener()));
      arg0.null((InputParseException)EnumDifficulty.const, (SQLAlterTableItem)(new BitmapRegionDecoder()));
      arg0.null((InputParseException)EnumDifficulty.int, (SQLAlterTableItem)(new ProximalHuber()));
      arg0.null((InputParseException)EnumDifficulty.null, (SQLAlterTableItem)(new BlockMycelium()));
      arg0.null((InputParseException)EnumDifficulty.new, (SQLAlterTableItem)(new Multinomial()));
      arg0.null((InputParseException)EnumDifficulty.null, (SQLAlterTableItem)(new ReflectiveGuiObjectAccess()));
   }

   public static ModifiableAttributeInstance null() {
      ModifiableAttributeInstance var0 = new ModifiableAttributeInstance(1343);
      GuiEditSign.null(var0);
      ProfileEntryStatValue.long(var0);
      Axis.class(var0);
      GuiSelectString.null(var0);
      ICommand.null(var0);
      ThreadingHelper.null(var0);
      NativeFastLayerIsland.null(var0);
      RegionIterator.class(var0);
      SQLAlterTableSetFileFormat.class(var0);
      JavaLateThreadRef.class(var0);
      BlockDir.class(var0);
      StatFs.long(var0);
      ChunkGeneratorOverworld.class(var0);
      ObjDoubleCharConsumer.class(var0);
      ItemSaddle.class(var0);
      VectorAdapter.class(var0);
      WorldGenLiquids.class(var0);
      ServerFinalMessage.long(var0);
      IntShortLongConsumer.class(var0);
      TileEntityFurnace.class(var0);
      Tick.class(var0);
      GSSInputStream.class(var0);
      CubicInterpolation.class(var0);
      CharObjMap.class(var0);
      ByteDoubleOpenHashMap.class(var0);
      SlotCrafting.class(var0);
      Operations.class(var0);
      EntitySilverfish.class(var0);
      Vec2lM.long(var0);
      Regions.class(var0);
      EntityArmorStand.class(var0);
      SimpleNetworkWrapper.class(var0);
      CommandCompleteParser.long(var0);
      AutoSave.class(var0);
      ReadOnlyException.class(var0);
      RocksMutableObject.class(var0);
      PairIndex.class(var0);
      DoubleShortFunction.class(var0);
      NBTTagDouble.class(var0);
      BluetoothServerSocket.class(var0);
      FloatIntBoolConsumer.class(var0);
      WorldBorder.long(var0);
      IRandomEntity.class(var0);
      FieldLocatorFixed.class(var0);
      EntityEnderCrystal.long(var0);
      FloatDoubleFunction.class(var0);
      PGJDBCMain.class(var0);
      EnumPlantType.class(var0);
      LongLongBoolConsumer.class(var0);
      LexerMoreAction.class(var0);
      CommandReload.class(var0);
      OdpsLexer.class(var0);
      ScaleXSpan.class(var0);
      BlockRedstoneRepeater.class(var0);
      TileEntityShulkerBox.class(var0);
      FloatLongLongConsumer.class(var0);
      FloatLongMap.long(var0);
      ItemFishFood.class(var0);
      messages_de.class(var0);
      ILootContainer.class(var0);
      BlockCake.class(var0);
      LongFloatObjFunction.class(var0);
      Filter.class(var0);
      ModelArmorStand.class(var0);
      ScramInvalidServerSignatureException.long(var0);
      EventBus.class(var0);
      CapabilityFluidHandler.class(var0);
      GuiButtonRecipe.class(var0);
      ComposePathEffect.class(var0);
      IntCache.class(var0);
      BlockMask.class(var0);
      EntityAILookIdle.class(var0);
      MysqlCreateFullTextCharFilterStatement.class(var0);
      ForgeBiomeRegistry.class(var0);
      IAnimationStateMachine.class(var0);
      ShortCharByteFunction.class(var0);
      RepeaterWeekend.long(var0);
      URLCoder.null(var0);
      ObjObjCharFunction.null(var0);
      StarRocksCreateResourceStatement.null(var0);
      PlayerDropsEvent.null(var0);
      GuiModsMissing.null(var0);
      RedshiftExprParser.class(var0);
      SqlPatternHash.null(var0);
      IResourceManagerReloadListener.null(var0);
      TransformerConsumer.null(var0);
      NaNHistory.null(var0);
      PathNavigateClimber.null(var0);
      null(var0);
      return var0;
   }

   public static CharShortFunction class(ModelBlockAnimation arg0, CharShortFunction arg1, int arg2, String arg3) {
      if (arg1.null(arg3, (int)10)) {
         arg1.null((String)arg3, (TileEntityStructure)arg0.null(EnumDifficulty.null, arg1.null(arg3), arg2));
      }

      return arg1;
   }

   public static CharShortFunction null(ModelBlockAnimation arg0, CharShortFunction arg1, int arg2, String arg3) {
      if (arg1.null(arg3, (int)9)) {
         CommandUsageException var4 = arg1.null(arg3, (int)10);

         for(int var5 = 0; var5 < var4.class(); ++var5) {
            var4.null(var5, arg0.null(EnumDifficulty.null, var4.null(var5), arg2));
         }
      }

      return arg1;
   }
}
